title: "Flag Master - Privacy Policy"
description: "Privacy Policy for Flag Master educational geography app"
url: "https://NovaOrion7.github.io"
baseurl: "/flag-master-privacy"

# GitHub Pages settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: NovaOrion7
twitter:
  username: NovaOrion7
social:
  name: NovaOrion7
  links:
    - https://github.com/NovaOrion7

# Analytics (disabled for privacy)
google_analytics: false

# Comments (disabled)
disqus:
  shortname: false

# Content settings
show_excerpts: true
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/